FROM ubuntu:24.04 AS builder
ENV DEBIAN_FRONTEND=noninteractive

# docker build -f Dockerfile.2404 -t ghcr.io/converged-computing/usernetes-python:lammps-flux-infiniband-openmpi-ucx-ubuntu2404 .

RUN apt-get update && apt-get install -y build-essential \
    tar \
    autoconf \
    automake \
    make \
    wget \
    git \
    gcc \
    g++ \
    zip \
    cmake \
    libblas-dev \
    liblapack-dev \
    libxml2 \
    libxml2-dev \
    hdf5-tools \
    libhdf5-dev \
    libboost-all-dev \
    && apt-get clean

# Utilities
RUN apt-get update && \
    apt-get -qq install -y --no-install-recommends \
        apt-utils \
        locales \
        ca-certificates \
        wget \
        man \
        git \
        flex \
        ssh \
        sudo \
        vim \
        luarocks \
        munge \
        lcov \
        ccache \
        lua5.2 \
        python3-dev \
        python3-pip \
        valgrind \
        jq && \
    rm -rf /var/lib/apt/lists/*

# Compilers, autotools
RUN apt-get update && \
    apt-get -qq install -y --no-install-recommends \
        build-essential \
        pkg-config \
        autotools-dev \
        libtool \
	libffi-dev \
        autoconf \
        automake \
        make \
        clang \
        clang-tidy \
        gcc \
        g++ && \
    rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade --ignore-installed --break-system-packages \
        "markupsafe==2.0.0" \
        coverage cffi ply six pyyaml "jsonschema>=2.6,<4.0" \
        sphinx sphinx-rtd-theme sphinxcontrib-spelling 
        
RUN apt-get update && \
    apt-get -qq install -y --no-install-recommends \
        libsodium-dev \
        libzmq3-dev \
        libczmq-dev \
        libjansson-dev \
        libmunge-dev \
        libncursesw5-dev \
        liblua5.2-dev \
        liblz4-dev \
        libsqlite3-dev \
        uuid-dev \
        libhwloc-dev \
        libs3-dev \
        libevent-dev \
        libarchive-dev \
        libpam-dev && \
    rm -rf /var/lib/apt/lists/*

# Testing utils and libs
RUN apt-get update && \
    apt-get -qq install -y --no-install-recommends \
        faketime \
        libfaketime \
        pylint \
        cppcheck \
        enchant-2 \
        aspell \
        aspell-en && \
    rm -rf /var/lib/apt/lists/*

RUN locale-gen en_US.UTF-8

RUN luarocks install luaposix

RUN apt-get purge -y libpmix-dev pmix-dev || true

# This needs to be done in one block because of a whiteout file.
ENV LOCAL_PREFIX=/usr/local
# This is a hack to not build the pmix docs - they don't expose a flag.
COPY ./Makefile.pmix-docs /tmp/Makefile.docs
RUN git clone --recurse-submodules --branch v5.0.3 https://github.com/openpmix/openpmix.git && \
    git clone --recurse-submodules --branch v3.0.4 https://github.com/openpmix/prrte.git && \
    cd openpmix && \
    ./autogen.pl && \
    ./configure --prefix=${LOCAL_PREFIX} --disable-static && \
    rm -rf docs && mkdir docs && cp /tmp/Makefile.docs ./docs/Makefile && \
    make -j 4 install && \
    ldconfig

RUN cd prrte && \
    ./autogen.pl && \
    PKG_CONFIG_PATH=${LOCAL_PREFIX}/lib/pkgconfig ./configure --prefix=${LOCAL_PREFIX} && \
    python3 -m pip install recommonmark --break-system-packages && \
    make -j 4 install && \
    ldconfig

ENV LANG=C.UTF-8
ARG FLUX_SECURITY_VERSION=0.14.0

WORKDIR /opt
RUN CCACHE_DISABLE=1 && \
    V=$FLUX_SECURITY_VERSION && \
    PKG=flux-security-$V && \
    URL=https://github.com/flux-framework/flux-security/releases/download && \
    wget ${URL}/v${V}/${PKG}.tar.gz && \
    tar xvfz ${PKG}.tar.gz && \
    cd ${PKG} && \
    ./configure --prefix=/usr --sysconfdir=/etc || cat config.log && \
    make -j 4 && \
    make install && \
    cd .. && \
    rm -rf flux-security-*

# Setup MUNGE directories & key
RUN mkdir -p /var/run/munge && \
    dd if=/dev/urandom bs=1 count=1024 > /etc/munge/munge.key && \
    chown -R munge /etc/munge/munge.key /var/run/munge && \
    chmod 600 /etc/munge/munge.key

ARG FLUX_CORE_VERSION="0.75.0"
RUN wget https://github.com/flux-framework/flux-core/releases/download/v${FLUX_CORE_VERSION}/flux-core-${FLUX_CORE_VERSION}.tar.gz && \
    tar xzvf flux-core-${FLUX_CORE_VERSION}.tar.gz && \
    cd flux-core-${FLUX_CORE_VERSION} && \
    ./configure --prefix=/usr --sysconfdir=/etc && \
    make clean && \
    make && \
    sudo make install

# Flux pmix (must be installed after flux core)
ARG FLUX_PMIX_VERSION=0.6.0
RUN wget https://github.com/flux-framework/flux-pmix/releases/download/v0.6.0/flux-pmix-0.6.0.tar.gz && \
    tar -xzvf flux-pmix-${FLUX_PMIX_VERSION}.tar.gz && \
    mv flux-pmix-${FLUX_PMIX_VERSION} /opt/flux-pmix && \
    cd /opt/flux-pmix && \
    ./configure --prefix=/usr && \
    make -j && \
    sudo make install

RUN sudo apt-get update
RUN sudo apt-get -qq install -y --no-install-recommends \
	libboost-graph-dev \
	libboost-system-dev \
	libboost-filesystem-dev \
	libboost-regex-dev \
	libyaml-cpp-dev \
	libedit-dev \
        libboost-dev \
        libyaml-cpp-dev \
	curl \
	libpthread-stubs0-dev

ENV LD_LIBRARY_PATH=/opt/miniconda/lib

ARG FLUX_SCHED_VERSION=0.45.0
RUN wget https://github.com/flux-framework/flux-sched/releases/download/v${FLUX_SCHED_VERSION}/flux-sched-${FLUX_SCHED_VERSION}.tar.gz && \
    tar -xzvf flux-sched-${FLUX_SCHED_VERSION}.tar.gz && \
    cd flux-sched-${FLUX_SCHED_VERSION} && \
    mkdir build && cd build && cmake ../ && \
    make && \
    sudo make install && \
    ldconfig

RUN apt-get update && \
    apt-get install -y pdsh libfabric-dev libfabric1 \
        openssh-client openssh-server \
        dnsutils telnet strace git g++ \
        unzip bzip2

WORKDIR /opt

# Install oras for saving artifacts
RUN export VERSION="1.2.0" && \
    curl -LO "https://github.com/oras-project/oras/releases/download/v${VERSION}/oras_${VERSION}_linux_amd64.tar.gz" && \
    mkdir -p oras-install/ && \
    tar -zxf oras_${VERSION}_*.tar.gz -C oras-install/ && \
    mv oras-install/oras /usr/local/bin/ && \
    rm -rf oras_${VERSION}_*.tar.gz oras-install/
    
# Additional packages
RUN apt-get update && apt-get install -y ibverbs-utils libibverbs-dev libibverbs1 && apt-get clean

ARG LAMMPS_VERSION="stable_2Aug2023" 
ARG UCX_VERSION="1.17.0"

# Install essential build tools and libraries
RUN apt-get update && apt-get install -y --no-install-recommends \
    dnsutils telnet strace cmake git g++ iputils-ping \
    build-essential \
    cmake \
    gfortran \
    git \
    wget \
    ca-certificates \
    libibverbs-dev \
    librdmacm-dev \
    libnuma-dev \
    libfftw3-dev \
    libfftw3-mpi-dev \
    python3-dev \
    libibumad-dev \    
    pkg-config \
    rdma-core \
    yacc \
    libcap-dev \
&& rm -rf /var/lib/apt/lists/*


# --- Install UCX ---
WORKDIR /tmp
RUN wget "https://github.com/openucx/ucx/releases/download/v${UCX_VERSION}/ucx-${UCX_VERSION}.tar.gz" && \
    tar -xzf "ucx-${UCX_VERSION}.tar.gz" && \
    cd "ucx-${UCX_VERSION}" && \
    ./configure --prefix=/opt/ucx --enable-optimizations --with-verbs --with-rdmacm --enable-cma --with-rc --with-ud --with-dc --with-mlx5-dv \
    && make -j$(nproc) && \
    make install && \
    cd /tmp && \
    rm -rf "ucx-${UCX_VERSION}"

# --- Install OpenMPI with UCX -
ENV PATH="/opt/ucx/bin:${PATH}" \
    LD_LIBRARY_PATH="/opt/ucx/lib:${LD_LIBRARY_PATH}" \
    PKG_CONFIG_PATH="/opt/ucx/lib/pkgconfig:${PKG_CONFIG_PATH}"

WORKDIR /opt
RUN wget https://download.open-mpi.org/release/open-mpi/v4.1/openmpi-4.1.2.tar.gz && \
    tar -xzvf openmpi-4.1.2.tar.gz && \
    cd openmpi-4.1.2 && \
    ./configure --with-ucx=/opt/ucx --without-verbs --prefix=/usr && \
    make && make install

# --- Install LAMMPS ---
WORKDIR /opt
RUN wget "https://github.com/lammps/lammps/archive/refs/tags/${LAMMPS_VERSION}.tar.gz" -O lammps.tar.gz && \
    tar -xzf lammps.tar.gz && \
    mv lammps-${LAMMPS_VERSION} lammps && \
    rm lammps.tar.gz

ENV LD_LIBRARY_PATH="/usr/lib:${LD_LIBRARY_PATH}"
ENV MPICC="/usr/bin/mpicc"
ENV MPICXX="/usr/bin/mpicxx"
ENV MPIF90="/usr/bin/mpif90"

WORKDIR /opt/lammps
RUN mkdir build && cd build && \
    cmake ../cmake \
    -D CMAKE_BUILD_TYPE=Release \
    -D BUILD_MPI=yes \
    -D BUILD_SHARED_LIBS=yes \
    -D LAMMPS_EXCEPTIONS=yes \
    -D CMAKE_INSTALL_PREFIX:PATH=/usr \
    -DPKG_REAXFF=yes \ 
    -DPKG_OPT=yes \
    -DFFT=FFTW3 \
    -D PKG_MOLECULE=yes \
    -D PKG_KSPACE=yes \
    -D PKG_MANYBODY=yes \
    -D PKG_RIGID=yes \
    && make -j4 && \
    make install && \
    rm -rf /tmp/lammps_source

RUN apt-get update && apt-get install -y net-tools ibverbs-utils ibutils perftest net-tools iputils-ping
WORKDIR /opt/lammps/examples/reaxff/HNS

# This needs to be done on node
# oras pull ghcr.io/converged-computing/rdma-infiniband:debian-12-tgz && \
#    tar -xzvf MLNX_OFED_LINUX-24.10-2.1.8.0-debian12.5-x86_64.tgz && \
#    cd MLNX_OFED_LINUX-24.10-2.1.8.0-debian12.5-x86_64
#    ./mlnxofedinstall --user-space-only --force
