apiVersion: flux-framework.org/v1alpha2
kind: MiniCluster
metadata:
  name: flux-osu-efa
spec:
  # sizes for experiment:
  # 32, 512
  # 16, 256
  # 8, 128
  # 4, 64
  size: 32
  tasks: 512
  logging:
    quiet: true
  flux:
    container:
      image: ubuntu:jammy
      disable: true
  containers:
    - image: ghcr.io/rse-ops/osu-benchmarks-efa:ubuntu-22.04@sha256:e889e5220b26e3a22b06aef56f62ad97518ec6ad00aaed25b158ca090a09a340
      command: osu_barrier
      resources:
        limits:
          vpc.amazonaws.com/efa: 1
        requests:
          vpc.amazonaws.com/efa: 1

