FROM ghcr.io/converged-computing/lc-toss4-base:toss.4.8-2.x86_64

COPY ./rpms /rpms

RUN dnf install -y perl rpmrebuild vim tcl-devel wget && \
    dnf install -y python39 python39-cffi python39-ply python39-yaml && \
    rpm -i ./rpms/pkgconf-pkg-config-1.4.2-1.el8.x86_64.rpm && \
    rpm -i ./rpms/mlnx-ofa_kernel-modules-25.01-0.6.0.1.0.5mofed.t4.x86_64.rpm && \
    rpm -i ./rpms/pmix-3.2.5-0.2mofed.t4.x86_64.rpm && \
    rpm -i ./rpms/kernel-headers-4.18.0-553.53.1.1toss.t4.x86_64.rpm && \
    rpm -i ./rpms/libnl3-* && \
    rpm -i ./rpms/libibverbs-* && \
    rpm -i ./rpms/logrotate-3.14.0-6.el8.x86_64.rpm 
    rpm -i ./rpms/munge-*
    rpm -i ./rpms/libibumad-2501mlnx56-1.2501060.x86_64.rpm && \
    rpm -i ./rpms/librdmacm-* && \
    rpm -i ./rpms/jansson-* && \
    rpm -i ./rpms/infiniband-diags-2501mlnx56-1.2501060.x86_64.rpm && \
    rpm -i ./rpms/zlib-devel-1.2.11-25.el8.x86_64.rpm && \
    rpm -i ./rpms/hwdata-0.314-8.8.el8.noarch.rpm && \
    rpm -i ./rpms/pciutils* && \
    rpm -i ./rpms/rdma-core-* && \
    rpm -i ./rpms/python3-* && \
    rpm -i ./rpms/libsodium-* && \
    rpm -i ./rpms/flux-security-0.14.0-1.t4.x86_64.rpm && \
    dnf install -y cairo-devel && \
    rpm -i ./rpms/flux-core-0.74.0-2.t4.x86_64.rpm && \
    rpm -i rpms/ibutils2-2.1.1-0.22100.MLNX20250123.g26a775d8.2501060.x86_64.rpm  && \
    rpm -i ./rpms/mlnx-tools-25.01-0.2501060.x86_64.rpm && \
    rpm -i ./rpms/lsof-4.93.2-1.el8.x86_64.rpm && \
    rpm -i ./rpms/ocl-icd-* && \
    rpm -i ./rpms/hwloc-* && \
    rpm -i ./rpms/lua-* && \
    rpm -i ./rpms/flux-core-0.74.0-2.t4.x86_64.rpm && \
    # rpmrebuild --edit-spec --package ./rpms/mlnx-ofa_kernel-25.04-0.6.0.1.0.2mofed.t4.x86_64.rpm
    # Comment out requires line for kernel version - isn't exact match. Save and copy as edited
    rpm -i ./rpms/mlnx-ofa_kernel-25.04-0.6.0.1.0.2mofed.t4.x86_64_edited.rpm && \
    rpm -i ./rpms/mlnx-ofa_kernel-devel* && \
    rpm -i ./rpms/mlnx-ofa_kernel-modules*
    rpm -i ./rpms/mlnx-ofa_kernel-devel* && \
    rpm -i ./rpms/mlnx-ofa_kernel-modules* && \
    rpm -i ./rpms/mlnx-ofa* && \
    # Note skipping cuda for now
    rpm -i rpms/ucx-1.18.0-12501060.1mofed.t4.x86_64.rpm && \
    rpm -i rpms/ucx-cma-1.18.0-12501060.1mofed.t4.x86_64.rpm && \
    # rpms/ucx-cuda-1.18.0-12501060.1mofed.t4.x86_64.rpm && \
    rpm -i rpms/ucx-devel-1.18.0-12501060.1mofed.t4.x86_64.rpm && \
    # rpms/ucx-gdrcopy-1.18.0-12501060.1mofed.t4.x86_64.rpm && \
    rpm -i rpms/ucx-ib-1.18.0-12501060.1mofed.t4.x86_64.rpm && \
    rpm -i rpms/ucx-rdmacm-1.18.0-12501060.1mofed.t4.x86_64.rpm && \
    rpm -i rpms/numactl-*  && \
    rpm -i rpms/lua-lpeg-1.0.1-6.el8.x86_64.rpm && \
    rpm -i rpm -i rpms/lua-* && \
    dnf install -y lua-filesystem lua-json lua-term && \
    rpm -i rpms/Lmod-8.7.7-1.1toss.t4.x86_64.rpm && \    
    dnf install -y java-openjdk-headless && \
    dnf install -y gcc-gfortran gcc-c++ && \
    rpm -i rpms/opensm-* && \
    rpm -i rpms/libpsm2-* && \
    rpm -i rpms/openmpi-4.1-gnu-4.1.6-3.1mofed.t4.x86_64.rpm && \
    rpm -i /rpms/fftw-*

WORKDIR /opt
ENV omb_source_tarball="osu-micro-benchmarks-${OMB_VERSION}.tar.gz"
ENV omb_url="http://mvapich.cse.ohio-state.edu/download/mvapich/${omb_source_tarball}"
RUN wget ${omb_url} --no-clobber && \
   tar -xzkf ${omb_source_tarball} 

ENV LD_LIBRARY_PATH="/usr/lib:${LD_LIBRARY_PATH}"
ENV MPICC="/opt/toss/openmpi/4.1/gnu/bin/mpicc"
ENV MPICXX="/opt/toss/openmpi/4.1/gnu/bin/mpicxx"
ENV MPIF90="/opt/toss/openmpi/4.1/gnu/bin/mpif90"

RUN cd /opt/osu-micro-benchmarks-7.5 && \
    ./configure CXX=mpicxx --prefix=/usr && \
    make -j4 && make install

# Be lazy and put them on the path!
ENV OSU_PREFIX=/usr/libexec/osu-micro-benchmarks/mpi
ENV PATH=$PATH:$OSU_PREFIX/one-sided:$OSU_PREFIX/pt2pt:$OSU_PREFIX/collective:$OSU_PREFIX/congestion:$OSU_PREFIX/startup

RUN wget "https://github.com/lammps/lammps/archive/refs/tags/stable_2Aug2023.tar.gz" -O lammps.tar.gz && \
    tar -xzf lammps.tar.gz && \
    mv lammps-stable_2Aug2023 /opt/lammps && \
    rm lammps.tar.gz


WORKDIR /opt/lammps
RUN mkdir build && cd build && \
    cmake ../cmake \
    -D CMAKE_BUILD_TYPE=Release \
    -D BUILD_MPI=yes \
    -D BUILD_SHARED_LIBS=yes \
    -D LAMMPS_EXCEPTIONS=yes \
    -D CMAKE_INSTALL_PREFIX:PATH=/usr \
    -D PKG_REAXFF=yes -D PKG_OPT=yes -D FFT=FFTW3 -D PKG_MOLECULE=yes -D PKG_KSPACE=yes -D PKG_MANYBODY=yes -D PKG_RIGID=yes \
    && make -j4 && \
    make install && \
    rm -rf /lammps

WORKDIR /opt/lammps/examples/reaxff/HNS
ENV PATH=$PATH:/opt/toss/openmpi/4.1/gnu/bin

# This needs to be done on node
# oras pull ghcr.io/converged-computing/rdma-infiniband:debian-12-tgz && \
#    tar -xzvf MLNX_OFED_LINUX-24.10-2.1.8.0-debian12.5-x86_64.tgz && \
#    cd MLNX_OFED_LINUX-24.10-2.1.8.0-debian12.5-x86_64
#    ./mlnxofedinstall --user-space-only --force
