apiVersion: "kubeflow.org/v1"
kind: PyTorchJob
metadata:
  name: pytorch-mnist
spec:
  pytorchReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          containers:
            - name: pytorch
              image: ghcr.io/converged-computing/pytorch-mnist:fashion
              imagePullPolicy: IfNotPresent
              resources:
                limits:
                  nvidia.com/gpu: 4
              command:
                - "/bin/bash"
                - "-c"
                - "time python3 /opt/pytorch-mnist/mnist.py --epochs=1 --backend=nccl --batch-size=128"
    Worker:
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          containers:
            - name: pytorch
              image: ghcr.io/converged-computing/pytorch-mnist:fashion
              resources:
                limits:
                  nvidia.com/gpu: 4
              imagePullPolicy: IfNotPresent
              command:
                - "/bin/bash"
                - "-c"
                - "time python3 /opt/pytorch-mnist/mnist.py --epochs=1 --backend=nccl --batch-size=128"
