apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: &name install-mlx-driver
  labels:
    app: *name
spec:
  selector:
    matchLabels:
      app: *name
  template:
    metadata:
      labels:
        app: *name
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node.kubernetes.io/instance-type
                operator: In
                values:
                - Standard_H16mr
                - Standard_H16mr_Promo
                - Standard_H16r
                - Standard_H16r_Promo
                - Standard_H8_Promo
                - Standard_HB120-16rs_v2
                - Standard_HB120-32rs_v2
                - Standard_HB120-64rs_v2
                - Standard_HB120-96rs_v2
                - Standard_HB120rs_v2
                - Standard_HB120-16rs_v3
                - Standard_HB120-32rs_v3
                - Standard_HB120-64rs_v3
                - Standard_HB120-96rs_v3
                - Standard_HB120rs_v3
                - Standard_HB60-15rs
                - Standard_HB60-30rs
                - Standard_HB60-45rs
                - Standard_HB60rs
                - Standard_NC24rs_v2
                - Standard_ND96amsr_A100_v4
                - Standard_ND96asr_v4
                - Standard_HC44rs

      hostNetwork: true
      hostPID: true
      containers:
      - image: ghcr.io/converged-computing/rdma-infiniband:ubuntu-22.04
        imagePullPolicy: Always
        name: *name
        command: ["/entrypoint.sh"] 
        args: ["installonly"]
        resources:
          requests:
            {}
          limits:
            {}
        securityContext:
          privileged: true
        volumeMounts:
        - name: actions
          mountPath: "/opt/actions"
        - name: hostmount
          mountPath: "/mnt/actions"
        - name: debs
          mountPath: "/mnt/debs"
      volumes:
      - name: debs
        hostPath:
          path: /opt/debs
          type: DirectoryOrCreate
      - name: hostmount
        hostPath:
          path: /opt/actions
          type: DirectoryOrCreate
      - name: actions
        configMap:
          name: install-driver-actions
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: install-driver-actions
  labels:
    app: install-mlx-driver
data:
  installonly: |
    #!/usr/bin/env bash
    set -eo pipefail

    SECONDS=0
    umount /mnt || true
    cd /opt/debs
    mount -o ro,loop ./MLNX_OFED_LINUX-24.04-0.7.0.0-ubuntu22.04-x86_64.iso /mnt
    # mount -o ro,loop MLNX_OFED_LINUX-5.6-2.0.9.0-ubuntu18.04-x86_64.iso /mnt
    # /mnt/mlnxofedinstall --force
    /mnt/mlnxofedinstall --without-dkms --add-kernel-support --kernel 5.15.0-1068-azure --without-fw-update --force
    # Going to run these manually for testing
    # modprobe -r nvme_rdma
    # /etc/init.d/openibd restart
    ip link
    tail -f /dev/null
    exit 0 
    check_ib="$(ip link | grep ib0)"
    echo $check_ib
    echo "installation completed in $SECONDS seconds"
---
