FROM ghcr.io/converged-computing/metric-lammps:latest
# docker build -t ghcr.io/converged-computing/metric-lammps:test-network .
RUN apt-get update && apt-get install -y iputils-ping dnsutils curl wget vim
