apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-server
spec:
  selector:
    matchLabels:
      run: ml-service
  replicas: 1
  template:
    metadata:
      labels:
        run: ml-service
    spec:
      containers:
      - name: ml-service
        image: ghcr.io/converged-computing/lammps-stream-ml:server-arm@sha256:b4effb8eb603a8672e5ab1160366a1922dfc4c6c5c53c62d1b11a1df32eee6e7
        # These should be secrets, but OK to test
        # I'm putting them here so you know they exist
        env:
          - name: SHELVE_SECRET_KEY
            value: noodles
          - name: JWT_SECRET_KEY
            value: noodles
          - name: SECRET_KEY
            value: "qbg(sz#n+4ji)(16xrn!gti%^ig#a5ni!sxg18nv7sv*n#h*7%"
        # EXTREMELY IMPORTANT: we need to set the host port so it's mapped to the
        # same as usernetes
        ports:
        - containerPort: 8080
          hostPort: 8080
        - containerPort: 80
          hostPort: 80

